server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Malutong0413#
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      timeout: 3000
      host: 127.0.0.1
      database: 1
      port: 6379
      password: 123456

